version: '3'
services:
  ap:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '${WEB_PORT:-13000}:3000'
      - '${SSH_PORT:-10022}:22'
    links:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - '${DB_PORT:-13306}:3306'
